# 项目相关配置
xqpark:
  # 名称
  name: xqpark
  # 文件上传路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务端口
  port: 8099
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.xqtc: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# 监控相关配置
endpoints:
  metrics:
    sensitive: false
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8

# Spring配置
spring:
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: @profileActive@
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/system/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xqtc.api.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /api/notice/*
  # 匹配链接
  urlPatterns: /api/*,/monitor/*,/tool/*

swagger:
  basic:
    enable: true
    username: xqtc
    password: jhkj@703
qiniu:
  accessKey: ElQ2uBSE0z38NcK87sfQJ49jcjwG-H_yWCkGcFUT
  secretKey: jUf8tMaMPsoySfAWI_fK8y-xx21YlfptVYemJMQu
  bucket: xqparkfile
  prefix: http://files.xqpark.cn